spring:
  datasource:
    master:
      username: root
      password: mysqladmin
      url: jdbc:mysql://127.0.0.1:3306/manydatasource1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver

    slave:
      username: root
      password: mysqladmin
      url: jdbc:mysql://127.0.0.1:3306/manydatasource2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true